services:
  # frontend:
  #   container_name: nextjs
  #   build:
  #     context: Frontend
  #     dockerfile: next.dockerfile
  #   restart: always
  #   ports: 3000:3000
  #   networks:
  #     - next-go
  #   depends_on: backend

  backend:
    container_name: go
    build:
      context: Backend
      dockerfile: go.dockerfile
    # restart: always
    environment:
      - DB_HOST=mongodb://mongo
      - DB_PORT=:27017
    expose:
      - 8080
    networks:
      - next-go
      - go-mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:8.0.3
    restart: always
    # environment:
    #   - MONGO_USER=mongo
    #   - MONGO_PASSWORD=mongo
    expose:
      - 27017
    networks:
      - go-mongo
    volumes:
      - mongo_data:/data/db
      - mongodb_config:/data/configdb

networks:
  next-go:
  go-mongo:

volumes:
  mongo_data:
  mongodb_config:
