services:
  frontend:
    container_name: nextjs
    build:
      context: Frontend
      dockerfile: next.dockerfile
    restart: on-failure
    environment:
      - NEXT_PUBLIC_API_URL=localhost:8080
      - NEXT_PRIVATE_API_URL=go:8080
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - next-go
    depends_on:
      - backend

  backend:
    container_name: go
    build:
      context: Backend
      dockerfile: go.dockerfile
    restart: on-failure
    environment:
      - DB_HOST=mongodb://mongo
      - DB_PORT=27017
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - next-go
      - go-mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:8.0.3
    restart: on-failure
    expose:
      - 27017
    networks:
      - go-mongo
    volumes:
      - mongo_data:/data/db
      - mongodb_config:/data/configdb

networks:
  next-go:
  go-mongo:

volumes:
  mongo_data:
  mongodb_config:
